### ISSUE TITLE
Als Unternehmen möchte ich eine Information darüber erhalten, dass für mein Unternehmen gespendet wurde um diese Spende annehmen zu können. (Manueller Versand)

### ISSUE THREAD

**Issue by Tapefabrik** [GeBeater/wir-vs-virus-hackathon-app#1]
- Bei bestätigter Zahlung wird der Inhalt eines Schreibens an das Unternehmen generiert.
- Die relevanten Informationen werden in einen S3 Bucket geschoben.
- Der Brief enthält alle Informationen die notwendig sind um sich online zu registrieren und das Geld abzurufen.

**Comment by djuerges** [comment]
@onepiers @GeBeater irgendjemand kann mir heute Abend nochmal ein kurzes, theoretisches HowTo geben wie das mit der S3 läuft.

**Comment by djuerges** [comment]
@Tapefabrik Offene Fragen: 
- Das Schreiben wird zu dem Zeitpunkt generiert, bei dem die erste Spende einging. Wollen wir dann wirklich schreiben, dass zum Beispiel 5€ eingegangen sind? Dann sollten wir den Text dahin gehend verändern, dass in der Zwischenzeit wahrscheinlich schon mehr Geld da ist. Sonst sehe ich ein Problem mit der Motivation für die Anmeldung und Abholung des Geldes.
- Mit welcher Absenderadresse firmieren wir?
-  "Liebes Team des" wird nicht bei jedem Firmennamen funktionieren und Grammatikregel in Abhängigkeit vom Firmennamen reinzubringen... forget it.
- Wie soll die initiale URL heißen, die Firmen besuchen? CoFund.de/getit ist vielleicht noch nicht das Optimum.
- Schritt 3. Hinterlegen Sie Ihr PayPal Konto -> wir bieten ja gar nicht nur PayPal an zum Auszahlen?
- Am Ende: Besuchen Sie für
weitere Informationen einfach Ihre persönliche Support-Seite: CoFund.de/company - diese Funktion gibt es nicht und ist noch gar nicht geplant oder müssen wir da noch was umsetzen?

[1585102859476-strandpauli-invitation.pdf](https://github.com/GeBeater/wir-vs-virus-hackathon-app/files/4381483/1585102859476-strandpauli-invitation.pdf)

**Comment by Tapefabrik** [comment]
- Das Schreiben wird zu dem Zeitpunkt generiert, bei dem die erste Spende einging. Wollen wir dann wirklich schreiben, dass zum Beispiel 5€ eingegangen sind? Dann sollten wir den Text dahin gehend verändern, dass in der Zwischenzeit wahrscheinlich schon mehr Geld da ist. Sonst sehe ich ein Problem mit der Motivation für die Anmeldung und Abholung des Geldes.
**Fair, nehmen wir mit auf. Den Betrag zu erwähnen und auf "da könnte noch mehr sein" hinzuweisen halte ich für den besten Weg.**
- Mit welcher Absenderadresse firmieren wir?
Die, der späteren Firmierung (wie heute diskutiert).
- "Liebes Team des" wird nicht bei jedem Firmennamen funktionieren und Grammatikregel in Abhängigkeit vom Firmennamen reinzubringen... forget it.
**Recht hast du, bauen wir um**
- Wie soll die initiale URL heißen, die Firmen besuchen? CoFund.de/getit ist vielleicht noch nicht das Optimum.
**Hier wählen wir etwas deutsches, Input kommt**
- Schritt 3. Hinterlegen Sie Ihr PayPal Konto -> wir bieten ja gar nicht nur PayPal an zum Auszahlen?
**Right, stimmt**
- Am Ende: Besuchen Sie für
- weitere Informationen einfach Ihre persönliche Support-Seite: CoFund.de/company - diese Funktion gibt es nicht und ist noch gar nicht geplant oder müssen wir da noch was umsetzen?
- Deprecated

**Comment by Tapefabrik** [comment]
[Anschreiben-CoFund.pdf](https://github.com/GeBeater/wir-vs-virus-hackathon-app/files/4389921/Anschreiben-CoFund.pdf)
Hier eine aktualisierte Version mit den Änderungen:

- Text umgebaut "da könnte auch noch mehr sein"
- Anschreiben: Liebe(r) UnternehmerIn
- PayPal: Abstrahiert
- Anmeldungs-URL: cofund.de/anmeldung
- Support-Seiten Text entfernt bzw. auf das Erstellen der eigenen Spendenseite geändert
